services:
  app:
    image: news_service:latest
    ports:
      - "8004:8004"
    volumes:
      - .:/app
      - ./key/ggmap-456203-58579108ac37.json:/app/key/ggmap-456203-58579108ac37.json
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8004
